server:
    port: 8085

spring:
    application:
        name: API-GATEWAY
    
    cloud:
        gateway:
            routes:
                - id: USER-SERVICE
                  uri: lb://USER-SERVICE
                  predicates:
                  - Path=/users/**

                - id: HOTEL-SERVICE
                  uri: lb://HOTEL-SERVICE
                  predicates:
                  - Path=/hotels/**,/staffs/**

                - id: RATINGS-SERVICE
                  uri: lb://RATINGS-SERVICE
                  predicates:
                  - Path=/ratings/**

# okta configuration for api gateway

okta:
    oauth2:
        issuer: https://dev-09064469.okta.com/oauth2/default
        audience: api://default
        client-id: 0oa93oykgx50xiMyF5d7
        client-secret: DOi8zU3TjbfweOpAHEi9JpDVwSFKVC32pQ8DxC7L
        scopes: openid, profile, email, offline_access


eureka:
    instance:
        hostname: localhost
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka